---
- hosts: node
  become: true
  tasks:
  #- name: instala httpd
  #  action: yum name=httpd state=installed
  - name: instala httpd
    package:
      name:
        - httpd
      state: latest    
  
  - name: copia index
    copy:
     src: "/etc/ansible/playbooks/tests/index.html"
     dest: "/var/www/html/"

  - name: restart httpd
    service:
     name: httpd
     state: restarted
     enabled: yes 

