---
- hosts: nodes
  become: true
  tasks:
  #- name: instala httpd
  #  action: yum name=httpd state=installed
  - name: instala httpd
    package:
      name:
        - httpd
      state: latest    

  - name: verifico si existe index.html 
    stat:
       path: "/var/www/html/index.html" 
    register: st_index

  - name: copia index
    copy:
     src: "/etc/ansible/playbooks/tests/index.html"
     dest: "/var/www/html/"
    when: not st_index.stat.exists

  - name: restart httpd
    service:
     name: httpd
     state: restarted
     enabled: yes 
    when: not st_index.stat.exists

