---
- hosts: node
  tasks:
  - name: instala httpd
    action: yum name=httpd state=installed
    tags:
     - install
  - name: copia index
    copy:
     src: "/etc/ansible/playbooks/tests/index.html"
     dest: "/var/www/html/"
    tags:
     - copy
  - name: restart httpd
    service:
     name: httpd
     state: restarted
     enabled: yes 
    tags: 
     - restart
  - name: stop httpd
    service:
     name: httpd
     state: stopped 
    tags: 
     - stop 

